More descriptive output in YamlSource related errors
Previously the errors were hard to diagnose:
ConfiguratorException: Failed to read io.jenkins.plugins.casc.yaml.YamlSource@5730c6
...
NoRouteToHostException: No route to host (Host unreachable)

With this change applied it's clearly visible what URL caused a problem.
It should work for every source that has sensible toString()
implementation.